/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AtCommand */

#ifndef _Included_AtCommand
#define _Included_AtCommand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AtCommand
 * Method:    Ql_SendAT
 * Signature: (Ljava/lang/String;Ljava/lang/String;[CJ)I
 */
JNIEXPORT jint JNICALL Java_AtCommand_Ql_1SendAT
  (JNIEnv *, jclass, jstring, jstring, jcharArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
