/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liteon_jt808_util_AtCommand */

#ifndef _Included_com_liteon_jt808_util_AtCommand
#define _Included_com_liteon_jt808_util_AtCommand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liteon_jt808_util_AtCommand
 * Method:    Ql_SendAT
 * Signature: (Ljava/lang/String;Ljava/lang/String;[CJ)I
 */
JNIEXPORT jint JNICALL Java_com_liteon_jt808_util_AtCommand_Ql_1SendAT
  (JNIEnv *, jclass, jstring, jstring, jcharArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
